---
enable_debug: false
configure_network: false
configure_storage: false
install_vagrant: false
libvirt_pkgs:
  - bridge-utils
  - libvirt
  - libvirt-devel
  - libguestfs
  - libguestfs-bash-completion
  - guestfs-tools
  - guestfs-tools-bash-completion
  - python3-libvirt
  - python3-lxml
  - qemu-kvm
  - qemu-user-static # for non-x86 cpu emulation
  - virt-install
  - virt-manager
vm_storage_dir: /home/libvirt/images
