virt_domain: "{{ ansible_domain }}"
ocp_public_ip: 127.0.0.1
fedora_pkgs:
  - krb5-workstation
  - chromium
  - evolution
  - hexchat
  - gimp
  - inkscape
  - asciidoctor
  - vim
  - guake
  - gvfs-mtp
  - rpmconf
  - patch
  - git
  - ansible
  - jq
  - docker
  - qemu-kvm
  - libvirt
  - virt-install
  - bridge-utils
  - virt-manager
  - libguestfs-tools
  - libguestfs-bash-completion
  - libguestfs
  - golang
  - dep
  - python3
  - ruby
  - awscli
  - python2-boto3
  - python2-boto
  - python3-boto
  - mpg123
  - fedora-workstation-backgrounds
  - gnome-backgrounds-extras
  - desktop-backgrounds-gnome
  - desktop-backgrounds-basic
  - f25-backgrounds-base
  - f26-backgrounds-base
  - f27-backgrounds-base
  - f28-backgrounds-base
  - f25-backgrounds-extras-base
  - f26-backgrounds-extras-base
  - f27-backgrounds-extras-base
  - f28-backgrounds-extras-base
  - f25-backgrounds-extras-xfce
  - f26-backgrounds-extras-xfce
  - f27-backgrounds-extras-xfce
  - f28-backgrounds-extras-xfce
