lenovo_pmfix: true
install_base: true
install_cloud: true
install_devel: true
install_artwork: false
install_codecs: false
install_chrome: false
install_daw: false

base_pkgs:
  - ansible
  - evolution
  - gimp
  - guake
  - gvfs-mtp
  - hexchat
  - inkscape
  - krb5-workstation
  - mpg123
  - vim
  - vim-X11

cloud_pkgs:
  - awscli
  - buildah
  - openscap
  - openscap-python3
  - openscap-scanner
  - openscap-utils
  - scap-security-guide
  - podman
  - podman-docker
  - python3-boto
  - python3-boto3
  - python3-operator-courier
  - python3-kubernetes
  - python3-openshift
  - python3-psutil
  - skopeo

devel_pkgs:
  - asciidoctor
  - btrfs-progs-devel
  - device-mapper-devel
  - fdupes
  - gcc
  - gcc-c++
  - git
  - git-credential-libsecret
  - golang
  - golang-docs
  - jq
  - patch
  - python3
  - python3-devel
  - rpmconf
  - ruby
  - vim-go
  - vim-golint
  - yamllint

daw_pkgs:
  - audacious
  - audacity
  - Cadence
  - fluid-soundfont-gm
  - fluid-soundfont-gs
  - guitarix
  - jalv
  - ladspa-swh-plugins
  - lv2-calf-plugins
  - lv2-devel
  - lv2-drumkv1
  - lv2-guitarix-plugins
  - lv2-samplv1
  - lv2-swh-plugins
  - lv2-synthv1
  - qjackctl
  - qmidiarp
  - qtractor
  - vmpk
  - yoshimi
  - zam-plugins
  - zynaddsubfx

rpmfusion_pkgs:
  - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
  - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
