---
# Fix an issue on certain laptops where suspend occurs when booting
# with the lid closed while docked and/or plugged in (forever reboot)
#
- name: Disable systemd laptop lid-close power mgmt
  block:
  - name: Create /etc/systemd/logind.conf if missing
    copy:
      src: /usr/lib/systemd/logind.conf
      dest: /etc/systemd/logind.conf
      force: false
      remote_src: true
    ignore_errors: true
  - name: Disable Lid Switch in /etc/logind.conf
    lineinfile:
      path: /etc/systemd/logind.conf
      line: "HandleLidSwitchExternalPower=ignore"
  become: true

- name: Disable Audio Popping on Intel HD Audio
  copy:
    src: alsa-base.conf
    dest: /etc/modprobe.d/alsa-base.conf
  become: true

- name: Disable Fedora hotspot popup annoyance
  file:
    path: /etc/NetworkManager/conf.d/20-connectivity-fedora.conf
    state: touch
  become: true

- name: List installed packages
  package_facts:
    manager: auto

- name: Install base packages
  dnf:
    name: "{{ base_pkgs }}"
    state: present
  become: true
  when: install_base | bool

- name: Install cloud and container tools
  block:
  - name: Install cloud and container packages
    dnf:
      name: "{{ cloud_pkgs }}"
      state: present

  - name: Configure Podman to use ISV container signing key
    get_url:
      url: https://www.redhat.com/security/data/55A34A82.txt
      dest: /etc/pki/rpm-gpg/ISV-Container-Signing-Key
      checksum: sha256:e90533f8907e14f417c4ab3761425a6d6f36074aa2d174ea6507320c5f62e6e0

  - name: Load vars from containers policy.json
    include_vars:
      file: /etc/containers/policy.json
      name: containers_policy

  - debug:
      var: containers_policy

  - name: Append ISV key to containers policy.json for community
    set_fact:
      containers_policy: "{{ containers_policy | default([]) | combine({'transports':{'docker':{'registry.redhat.io/redhat/community-operator-index':[{'type':'signedBy','keyType':'GPGKeys','keyPath':'/etc/pki/rpm-gpg/ISV-Container-Signing-Key'}]}}}, recursive=True) }}"

  - name: Append ISV key to containers policy.json for certified
    set_fact:
      containers_policy: "{{ containers_policy | default([]) | combine({'transports':{'docker':{'registry.redhat.io/redhat/certified-operator-index':[{'type':'signedBy','keyType':'GPGKeys','keyPath':'/etc/pki/rpm-gpg/ISV-Container-Signing-Key'}]}}}, recursive=True) }}"

  - name: Append ISV key to containers policy.json for marketplace
    set_fact:
      containers_policy: "{{ containers_policy | default([]) | combine({'transports':{'docker':{'registry.redhat.io/redhat/redhat-marketplace-index':[{'type':'signedBy','keyType':'GPGKeys','keyPath':'/etc/pki/rpm-gpg/ISV-Container-Signing-Key'}]}}}, recursive=True) }}"

  - name: write var to test file
    copy:
      content: "{{ containers_policy | to_nice_json }}"
      dest: /etc/containers/policy.json
  become: true
  when: install_cloud | bool

- name: Install CSB worksuite
  dnf:
    name: "{{ csb_pkgs }}"
    state: present
  become: true
  when: install_csb | bool or
    ansible_local.csb is defined

- name: Install and Configure Dev Environment
  block:
  - name: Install developer tools and frameworks
    dnf:
      name: "{{ devel_pkgs }}"
      state: present
    become: true

  - name: Configure git credential helper
    ini_file:
      path: "{{ ansible_user_dir }}/.gitconfig"
      section: credential
      option: helper
      value: /usr/libexec/git-core/git-credential-libsecret
      mode: "0600"

  - name: Setup vim indentation of json
    copy:
      src: json.vim
      dest: "{{ ansible_user_dir }}/.vim/ftplugin/"

  - name: Setup vim indentation of yaml
    copy:
      src: yaml.vim
      dest: "{{ ansible_user_dir }}/.vim/ftplugin/"
  when: install_devel | bool

- name: Install Chromium (Fedora)
  block:
  - name: Install chromium package
    dnf:
      name: chromium
      state: present

  - name: Enable SSO for Chrome/Chromium in Incognito mode
    copy:
      src: 00_gssapi_incognito.json
      dest: /etc/chromium/policies/recommended/
  become: true
  when:
  - install_chromium | bool

- name: Enable RPM Fusion (including non-free) multimedia codecs
  block:
  - name: Import RPM Fusion (free) GPG Key
    rpm_key:
      key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
      fingerprint: E9A4 91A3 DE24 7814 E7E0 67EA E06F 8ECD D651 FF2E

  - name: Import RPM Fusion (non-free) GPG Key
    rpm_key:
      key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
      fingerprint: 79BD B88F 9BBF 7391 0FD4 095B 6A2A F961 9484 3C65

  - name: Install RPM Fusion repos
    dnf:
      name: "{{ rpmfusion_pkgs }}"
      state: present

  - name: Install multimedia codecs
    dnf:
      name: "{{ codec_pkgs }}"
      state: present
  become: true
  when: install_codecs | bool

- name: Install Google Chrome
  block:
  - name: Import Google Linux GPG Key
    rpm_key:
      key: https://dl.google.com/linux/linux_signing_key.pub
      fingerprint: 4CCA 1EAF 950C EE4A B839 76DC A040 830F 7FAC 5991

  - name: Download and install Google Chrome RPM
    dnf:
      name: "https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm"
      state: present

  - name: Enable SSO for Chrome/Chromium in Incognito mode
    copy:
      src: 00_gssapi_incognito.json
      dest: /etc/opt/chrome/policies/recommended/
  become: true
  when: install_chrome | bool

- name: Install GNOME extensions
  dnf:
    name: "{{ gnome_exts }}"
    state: present
  become: true
  when: "'gnome-shell' in ansible_facts.packages"

- name: Prune unwanted packages
  block:
  - name: prune cloud packages
    dnf:
      name: "{{ cloud_pkgs }}"
      state: absent
    when: not install_cloud | bool

  - name: prune devel packages
    dnf:
      name: "{{ devel_pkgs }}"
      state: absent
    when: not install_devel | bool

  - name: prune base packages
    dnf:
      name: "{{ base_pkgs }}"
      state: absent
    when: not install_base | bool

  - name: prune multimedia codecs
    dnf:
      name: "{{ codec_pkgs }}"
      state: absent
    when: not install_codecs | bool

  - name: prune csb packages
    dnf:
      name: "{{ csb_pkgs }}"
      state: absent
    when: not install_csb | bool
  become: true
  when: prune_pkgs | bool
