---
# Fix an issue on certain laptops where suspend occurs when booting
# with the lid closed while docked and/or plugged in (forever reboot)
- name: Disable systemd laptop lid-close power mgmt
  lineinfile:
    path: /etc/systemd/logind.conf
    line: "HandleLidSwitchExternalPower=ignore"
  when: lenovo_pmfix | bool

- name: Install base packages
  dnf:
    name: "{{ base_pkgs }}"
    state: present
  when: install_base | bool

- name: Install cloud and container tools
  dnf:
    name: "{{ cloud_pkgs }}"
    state: present
  when: install_cloud | bool

- name: Install developer tools and frameworks
  dnf:
    name: "{{ devel_pkgs }}"
    state: present
  when: install_devel | bool

- name: Configure git credential helper
  ini_file:
    path: ~/.gitconfig
    section: credential
    option: helper
    value: /usr/libexec/git-core/git-credential-libsecret
    mode: "0600"
  become: false

- name: Setup vim indentation of json
  copy:
    src: json.vim
    dest: ~/.vim/ftplugin/json.vim
  become: false

- name: Setup vim indentation of yaml
  copy:
    src: yaml.vim
    dest: ~/.vim/ftplugin/yaml.vim
  become: false

- name: Install Chromium (Fedora)
  dnf:
    name: chromium
    state: present
  when:
  - not install_chrome | bool
  - not install_codecs | bool

- name: Install Fedora artwork
  dnf:
    name: f{{ item }}-backgrounds-base,f{{ item }}-backgrounds-extras-base,f{{ item }}-backgrounds-extras-gnome,f{{ item }}-backgrounds-extras-xfce
    state: present
  with_items:
  - "{{ query('sequence', 'start=21 end={{ ansible_distribution_version }}') }}"
  when: install_artwork | bool

- name: Enable RPM Fusion (including non-free) multimedia codecs
  block:
  - name: Import RPM Fusion (free) GPG Key
    rpm_key:
      key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
      fingerprint: E9A4 91A3 DE24 7814 E7E0 67EA E06F 8ECD D651 FF2E

  - name: Import RPM Fusion (non-free) GPG Key
    rpm_key:
      key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
      fingerprint: 79BD B88F 9BBF 7391 0FD4 095B 6A2A F961 9484 3C65

  - name: Install RPM Fusion repos
    dnf:
      name: "{{ rpmfusion_pkgs }}"
      state: present

  - name: Install multimedia codecs
    dnf:
      name: '@Multimedia'
      state: present

  # Chromium-freeworld enables non-free multimedia streaming, Bluejeans Live and WebEx screensharing versus fedora chromium:
  - name: Install chromium-freeworld
    dnf:
      name: chromium-freeworld
      state: present
    when: not install_chrome | bool
  when: install_codecs | bool

- name: Install Google Chrome
  block:
  - name: Import Google Linux GPG Key
    rpm_key:
      key: https://dl.google.com/linux/linux_signing_key.pub
      fingerprint: 4CCA 1EAF 950C EE4A B839 76DC A040 830F 7FAC 5991

  - name: Download and install Google Chrome RPM
    dnf:
      name: "https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm"
      state: present
  when: install_chrome | bool

- name: Disable Fedora Chromium package (replaced by chrome and/or chromium-freeworld)
  dnf:
    name: chromium
    state: absent
  when: install_chrome | bool or
        install_codecs | bool

- name: Install Digital Audio Workstation
  dnf:
    name: "{{ daw_pkgs }}"
    state: present
  when: install_daw | bool
