---
- name: Install base packages
  dnf:
    name: "{{ base_pkgs }}"
    state: present

- name: Install cloud and container tools
  dnf:
    name: "{{ cloud_pkgs }}"
    state: present

- name: Install developer tools and frameworks
  dnf:
    name: "{{ dev_pkgs }}"
    state: present
  when: install_dev == true

- name: Install Fedora artwork
  dnf:
    name: "{{ artwork_pkgs }}"
    state: present
  when: install_artwork == true
