install_drivers: false
install_usenet: false
install_media_players: false
install_spotify: false

missing_steam_libs:
- libbz2.i686

missing_gstreamer_plugins:
- gstreamer1-plugin-libav

media_players:
- vlc
- mpv
- celluloid
- smplayer
