---
- name: Create Downloads directory
  file:
    path: "{{ ansible_user_dir }}/Downloads"
    state: directory

- name: Create $HOME/bin directory
  file:
    path: "{{ ansible_user_dir }}/bin"
    state: directory

- name: Download CodeReady Containers
  get_url:
    url: http://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/crc-linux-amd64.tar.xz
    dest: "{{ ansible_user_dir }}/Downloads/crc-linux-amd64.tar.xz"

- name: Extract crc archive
  unarchive:
    src: "{{ ansible_user_dir }}/Downloads/crc-linux-amd64.tar.xz"
    remote_src: true
    dest: "{{ crc_dest_dir }}"
    exclude: "*/LICENSE"
    extra_opts:
    - --strip-components=1

- name: fetch crc homedir state
  stat:
    path: "{{ ansible_user_dir }}/.crc"
  register: crc_dir

- name: crc homedir
  debug:
    var: crc_dir

- name: Disable COW for crc dir if btrfs
  block:
  - name: Purge crc cache dir
    file:
      path: "{{ ansible_user_dir }}/.crc"
      state: absent

  - name: Enable btrfs nodatacow for crc dir
    file:
      path: "{{ ansible_user_dir }}/.crc"
      attributes: +C
      state: directory
  when:
  - "not 'C' in crc_dir.stat.attr_flags"
  - "'btrfs' in ansible_mounts | json_query('[?mount == `/home`].fstype')"
