---
- name: Install Steam and Wine
  dnf:
    name:
      - steam
      - wine
      - protontricks
      - discord
    state: present
  become: true

- name: Install Missing GStreamer Plugins
  dnf:
    name: "{{ missing_gstreamer_plugins }}"
    state: present
  become: true

- name: Install Media Players
  dnf:
    name: "{{ media_players }}"
    state: present
  when: install_media_players | bool
  become: true

- name: Install Spotify
  block:
  - name: Install Spotify LPF package
    dnf:
      name: lpf-spotify-client
      state: present

  - name: Add current user to the pkg-build group
    user:
      name: "{{ ansible_user_id }}"
      groups: pkg-build
      append: true
  when: install_spotify | bool
  notify: lpf-update
  become: true

- name: Install Gaming Hardware Drivers and Utilities
  block:
  - name: Get list of Graphics Adapters
    shell: lspci | grep VGA
    register: vga_devices

  - name: Install NVIDIA drivers
    dnf:
      name: nvidia-driver
      state: present
    when: '"NVIDIA" in vga_devices.stdout'

  - name: Get list of USB Devices
    shell: lsusb
    register: usb_devices

  - name: Download OpenRazer DNF Repo
    get_url:
      url: https://download.opensuse.org/repositories/hardware:razer/Fedora_{{ ansible_distribution_version }}/hardware:razer.repo
      dest: /etc/yum.repos.d/hardware:razer.repo
      owner: root
    when: '"Corsair" in usb_devices.stdout or "Razer" in usb_devices.stdout'

  - name: Install Corsair Utilities
    dnf:
      name:
      - ckb-next
      state: present
    when: '"Corsair" in usb_devices.stdout'

  - name: Install Razer Utilities
    block:
    - name: Install OpenRazer and Polychromatic GUI
      dnf:
        name:
        - openrazer-meta
        - polychromatic
        state: present

    - name: Create the plugdev group
      group:
        name: plugdev
        gid: 46
        state: present

    - name: Add current user to the plugdev group
      user:
        name: "{{ ansible_user_id }}"
        groups: plugdev
        append: true
    when: '"Razer" in usb_devices.stdout'
  become: true
  when: install_drivers | bool

- name: Install USENET tools
  block:
  - name: install sabnzbd deps
    dnf:
      name:
      - python3-apprise
      - python3-wheel
      - python3-cheetah
      - python3-guessit
      - python3-cherrypy
      - python3-configobj
      - python3-feedparser
      - par2cmdline
      - unrar

  - name: install sabyenc3 python module
    pip:
      name:
      - sabyenc3
      - sabctools
      - puremagic
      state: present

  - name: clone SABnzbd git repo in into /usr/local/src
    git:
      repo: https://github.com/sabnzbd/sabnzbd
      dest: /usr/local/src/sabnzbd

  - name: create script to launch sabnzbd
    copy:
      src: ./roles/extras/files/sabnzbd
      dest: /usr/local/bin/sabnzbd
      mode: 0755
  become: true
  when: install_usenet | bool

- name: Configure remote access for sabnzbd
  block:
  - name: create systemd unit for sabnzbd
    copy:
      src: sabnzbd.service
      dest: /etc/systemd/system/sabnzbd.service

  - name: create sabnzbd service account
    user:
      name: sabnzbd
      create_home: true

  - name: add sabnzbd service (port 8080) to home firewall zone
    firewalld:
      service: jenkins
      zone: home
      state: enabled
      permanent: true
      immediate: true
    notify:
    - firewall-interfaces
  become: true
  when:
  - remote_usenet | bool
  - install_usenet | bool

- name: Install Fedora artwork
  dnf:
    name: f{{ item }}-backgrounds-base,f{{ item }}-backgrounds-extras-base,f{{ item }}-backgrounds-extras-gnome,f{{ item }}-backgrounds-extras-xfce
    state: present
  with_items:
  - "{{ query('sequence', 'start=21 end={{ ansible_distribution_version }}') }}"
  become: true
  when: install_artwork | bool

- name: Install Digital Audio Workstation
  dnf:
    name: "{{ daw_pkgs }}"
    state: present
  become: true
  when: install_daw | bool

- name: Install Plex Media Server
  block:
  - name: Setup Plex RPM repo
    copy:
      src: plex.repo
      dest: /etc/yum.repos.d/plex.repo

  - name: Import RPM Fusion (non-free) GPG Key
    rpm_key:
      key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
      fingerprint: 79BD B88F 9BBF 7391 0FD4 095B 6A2A F961 9484 3C65

  - name: Install Plex Media Server package
    dnf:
      name: "{{ media_servers }}"
      state: present
      allowerasing: true

  - name:
    firewalld:
      zone: home
      port: 32400/tcp
      state: enabled
      permanent: true
      immediate: true
    notify:
    - firewall-interfaces
  become: true
  when: install_plex | bool
