---
- name: Install Steam and Wine
  dnf:
    name:
      - steam
      - wine
      - protontricks
    state: present
  become: true

- name: Install Missing GStreamer Plugins
  dnf:
    name: "{{ missing_gstreamer_plugins }}"
    state: present
  become: true

- name: Install Media Players
  dnf:
    name: "{{ media_players }}"
    state: present
  when: install_media_players | bool
  become: true

- name: Install Spotify
  block:
  - name: Install Spotify LPF package
    dnf:
      name: lpf-spotify-client
      state: present

  - name: Add current user to the pkg-build group
    user:
      name: "{{ ansible_user_id }}"
      groups: pkg-build
      append: true
  when: install_spotify | bool
  notify: lpf-update
  become: true

- name: Install Gaming Hardware Drivers and Utilities
  block:
  - name: Get list of Graphics Adapters
    shell: lspci | grep VGA
    register: vga_devices

  - name: Install NVIDIA drivers
    dnf:
      name: nvidia-driver
      state: present
    when: '"NVIDIA" in vga_devices.stdout'

  - name: Get list of USB Devices
    shell: lsusb
    register: usb_devices

  - name: Download OpenRazer DNF Repo
    get_url:
      url: https://download.opensuse.org/repositories/hardware:razer/Fedora_{{ ansible_distribution_version }}/hardware:razer.repo
      dest: /etc/yum.repos.d/hardware:razer.repo
      owner: root
    when: '"Corsair" in usb_devices.stdout or "Razer" in usb_devices.stdout'

  - name: Install Corsair Utilities
    dnf:
      name:
      - ckb-next
      state: present
    when: '"Corsair" in usb_devices.stdout'

  - name: Install Razer Utilities
    block:
    - name: Install OpenRazer and Polychromatic GUI
      dnf:
        name:
        - openrazer-meta
        - polychromatic
        state: present

    - name: Create the plugdev group
      group:
        name: plugdev
        state: present

    - name: Add current user to the plugdev group
      user:
        name: "{{ ansible_user_id }}"
        groups: plugdev
        append: true
    when: '"Razer" in usb_devices.stdout'
  become: true
  when: install_drivers | bool

- name: Install USENET tools
  block:
  - name: install sabnzbd deps
    dnf:
      name:
      - python3-apprise
      - python3-wheel
      - python3-cheetah
      - python3-guessit
      - python3-cherrypy
      - python3-configobj
      - python3-feedparser
      - par2cmdline
      - unrar

  - name: install sabyenc3 python module
    pip:
      name:
      - sabyenc3
      - sabctools
      - puremagic
      state: present

  - name: clone SABnzbd git repo in into /usr/local/src
    git:
      repo: https://github.com/sabnzbd/sabnzbd
      dest: /usr/local/src/sabnzbd

  - name: create script to launch sabnzbd
    copy:
      src: ./roles/extras/files/sabnzbd
      dest: /usr/local/bin/sabnzbd
      mode: 0755
  become: true
  when: install_usenet | bool

- name: Install Fedora artwork
  dnf:
    name: f{{ item }}-backgrounds-base,f{{ item }}-backgrounds-extras-base,f{{ item }}-backgrounds-extras-gnome,f{{ item }}-backgrounds-extras-xfce
    state: present
  with_items:
  - "{{ query('sequence', 'start=21 end={{ ansible_distribution_version }}') }}"
  become: true
  when: install_artwork | bool

- name: Install Digital Audio Workstation
  dnf:
    name: "{{ daw_pkgs }}"
    state: present
  become: true
  when: install_daw | bool
