---
# Deprecated in favor of RHEL CSB
# Provided for minimal configuration of a non-CSB Fedora install
- name: Setup Chromium for legacy RH Kerberos SSO
  copy:
    src: redhat-corp.json
    dest: /etc/chromium/policies/managed/

- name: Create Chrome symlink for Kerberos SSO
  file:
    src: /etc/chromium
    path: /etc/opt/chrome
    state: link

- name: Install RH IPA cert
  copy:
    src: ca.crt
    dest: /etc/ipa/

- name: Configure Kerberos for RH IPA
  copy:
    src: redhat-idm.conf
    dest: /etc/krb5.conf.d/

- name: Configure CUPS for RH Campuses
  copy:
    src: cups-browsed.conf
    dest: /etc/cups/
  notify:
    - restart cups

- name: Install RPMs for RH VPN
  dnf:
    name:
    - redhat-internal-cert-install-0.1-29.el7.noarch.rpm
    - redhat-internal-NetworkManager-openvpn-profiles-0.1-55.el7.noarch.rpm
    - redhat-internal-NetworkManager-openvpn-profiles-non-gnome-0.1-55.el7.noarch.rpm
    - BlueJeans_2.32.1.3.rpm
    - slack-4.29.149-0.1.el8.x86_64.rpm
    - teams-1.5.00.23861-1.x86_64.rpm
    - zoom-5.13.7.683-1.x86_64.rpm
    - Bitwarden-1.33.0-x86_64.rpm
    state: present
    disable_gpg_check: true
  when:
  - ansible_connection == 'local'

- name: Install beaker-client yum repo
  copy:
    src: beaker-client.repo
    dest: /etc/yum.repos.d/beaker-client.repo

- name: Install RH beaker-client packages
  dnf:
    name:
      - beaker-client
      - beaker-redhat
    state: present
