---
- name: start_libvirt_net
  virt_net:
    name: "{{ libvirt_network_name }}"
    command: start
  become: true

- name: start_default_pool
  virt_pool:
    name: default
    command: start
  become: true

- name: start_dns_libvirt
  systemd:
    name: dns-libvirt-{{ libvirt_network_device }}
    state: started
    enabled: true
  become: true
