- name: Install Docker-Machine-KVM
  hosts: all
  tasks:
  
  - name: Install Docker-Machine-KVM driver
    #shell: curl -L https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.10.0/docker-machine-driver-kvm-centos7 -o /usr/local/bin/docker-machine-driver-kvm
    get_url:
      url: https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.10.0/docker-machine-driver-kvm-centos7
      dest: /usr/local/bin/docker-machine-driver-kvm
      mode: 0755
