# This playbook installs optional, non-work related extras for off-hours use only :)
# Don't use the "become" flag with this playbook, or your user account won't get added to the plugdev group.
# Set the variables below according to preference, but I recommend to enable them both.
# 
# To run locally, define "localhost ansible_connection=local" in your hosts inventory and run:
# ansible-playbook -K -i hosts playbooks/extras.yml
#
# To run remotely, define your remote machines in your hosts inventory and run:
# ansible-playbook -ku <username> -i hosts playbooks/extras.yml

- hosts: all
  roles:
  - role: extras 
    vars:
      install_drivers: true
      install_usenet: true
