---
# This playbook installs Minikube v1.16.0 (K8s v1.20-beta). This is a bit dated, and pending modernization.
# Don't use the become flag with this playbook. The minikube binary will install to your user's home directory.
#
# To install this locally, make sure to add "localhost ansible_connection=local" to your hosts inventory and run:
# ansible-playbook -K -i hosts playbooks/minikube.yml
#
# After installation, to use minikube just run:
# minikube start

- hosts: all
  roles:
  - minikube
